### ISSUE TITLE
Add Score-Board

### ISSUE THREAD

**Issue by Shubhankar249** [Shubhankar249/Jeero-Kuttas#1]
Add a score board for user and computer, UI and UX can also be improved.

**Comment by Tripathi-Vaibhav** [comment]
Will it be okay if I make the scoreboard like this and in between them the board will fit .
What do you say ?
![Screenshot from 2020-10-06 13-25-41](https://user-images.githubusercontent.com/44133912/95174548-da7e3780-07d7-11eb-9666-bd6428269f86.png)

**Comment by Shubhankar249** [comment]
Yup, seems good.

**Comment by Tripathi-Vaibhav** [comment]
Cool then. I'll send you pull request as soon as possible.

**Comment by shashwatbangar** [comment]
Hello @Shubhankar249 , Is this question still open to solve? i would like to make this score board !!

**Comment by Shubhankar249** [comment]
@Tripathi-Vaibhav  are you still working on this?

**Comment by Tripathi-Vaibhav** [comment]
Yes @Shubhankar249 .. just some bugs left to resolve .. functionality is ready

**Comment by shashwatbangar** [comment]
so should I start working on this project or not? @Shubhankar249

**Comment by Tripathi-Vaibhav** [comment]
Is this looks good ?
![Screenshot from 2020-10-07 11-47-59](https://user-images.githubusercontent.com/44133912/95294555-1a562500-0893-11eb-8e85-8652f8e0d4e1.png)

**Comment by Tripathi-Vaibhav** [comment]
@Shubhankar249 Should I send you the pull request ?

**Comment by Shubhankar249** [comment]
Yes, @Tripathi-Vaibhav go ahead.

**Comment by Shubhankar249** [comment]
@shashwatbangar, I am going to open similar issues in other repos in a day or two, you can contribute there, if you like.
